// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThanhThoaiRestaurant.Models;

#nullable disable

namespace ThanhThoaiRestaurant.Migrations
{
    [DbContext(typeof(QuanLyNhaHangContext))]
    [Migration("20231014182646_TenCuaMigration")]
    partial class TenCuaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.BanAn", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiBa")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiBA");

                    b.HasKey("MaBan");

                    b.ToTable("BanAn", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietDh", b =>
                {
                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("MaDonHang")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("SoLuongMmdh")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongMMDH");

                    b.Property<string>("TenMonAnDh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenMonAnDH");

                    b.HasKey("MaMon", "MaDonHang")
                        .HasName("PK_DH");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ChiTietDH", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietGm", b =>
                {
                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("MaPhieuGm")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaPhieuGM")
                        .IsFixedLength();

                    b.Property<int>("SoLuongCt1")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongCT1");

                    b.HasKey("MaMon", "MaPhieuGm")
                        .HasName("PK_CTGM");

                    b.HasIndex("MaPhieuGm");

                    b.ToTable("ChiTietGM", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietHd", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("SoLuongCt")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongCT");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MaHd", "MaMon")
                        .HasName("PK_CTHD");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHD", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DatBan", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("MaLichHen")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime");

                    b.Property<int>("SoKhach")
                        .HasColumnType("int");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.Property<int>("TrangThaiLh")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiLH");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.ToTable("DatBan", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DonHang", b =>
                {
                    b.Property<string>("MaDonHang")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<int>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TrangThaiDh")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiDH");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaKH");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.GioHang", b =>
                {
                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<int>("SoLuongMM")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongMM");

                    b.Property<float>("ThanhTien")
                        .HasColumnType("real")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaMon", "MaKH");

                    b.HasIndex("MaKH");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<string>("MaPhieuGg")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaPhieuGG")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayHd")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayHD");

                    b.Property<string>("TenMonAnHd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenMonAnHD");

                    b.Property<decimal>("TienGiam")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TienTt")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TienTT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MaHd");

                    b.HasIndex("MaPhieuGg");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"), 1L, 1);

                    b.Property<string>("DiaChiKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChiKH");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<decimal>("DoanhSo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmailKh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EmailKH");

                    b.Property<string>("GioiTinhKh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinhKH");

                    b.Property<DateTime>("NgaySinhKh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinhKH");

                    b.Property<DateTime>("NgayTg")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTG");

                    b.Property<string>("Sdtkh")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("SDTKH")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKH");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"), 1L, 1);

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float")
                        .HasColumnName("GiaBan");

                    b.Property<int?>("GioHangMaKH")
                        .HasColumnType("int");

                    b.Property<int?>("GioHangMaMon")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<int?>("MaNhom")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("MoTaDai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaNhom");

                    b.HasIndex("GioHangMaMon", "GioHangMaKH");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NguoiDung", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailNd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("EmailND")
                        .IsFixedLength();

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TenDangNhap")
                        .HasName("PK_NguoiDung_1");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("Cccdnv")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("CCCDNV")
                        .IsFixedLength();

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChiNv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChiNV");

                    b.Property<string>("EmailNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EmailNV");

                    b.Property<string>("GioiTinhNv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinhNV");

                    b.Property<DateTime>("NgaySinhNv")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinhNV");

                    b.Property<DateTime>("NgayVl")
                        .HasColumnType("date")
                        .HasColumnName("NgayVL");

                    b.Property<string>("Sdtnv")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("SDTNV")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNV");

                    b.HasKey("MaNv");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhomMonAn", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"), 1L, 1);

                    b.Property<string>("TenNhom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomMonAn", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGiamGium", b =>
                {
                    b.Property<string>("MaPhieuGg")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaPhieuGG")
                        .IsFixedLength();

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("LoaiMa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PhanTram")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongPhieu")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiPgg")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiPGG");

                    b.HasKey("MaPhieuGg");

                    b.ToTable("PhieuGiamGia");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGoiMon", b =>
                {
                    b.Property<string>("MaPhieuGm")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaPhieuGM")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayGm")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayGM");

                    b.Property<string>("TenMonAnPgm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenMonAnPGM");

                    b.HasKey("MaPhieuGm");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaHd");

                    b.ToTable("PhieuGoiMon", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietDh", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDhs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("fk_DH_CTDH");

                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietDhs")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MonAn_CTDH");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietGm", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietGms")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MonAn_CTGM");

                    b.HasOne("ThanhThoaiRestaurant.Models.PhieuGoiMon", "MaPhieuGmNavigation")
                        .WithMany("ChiTietGms")
                        .HasForeignKey("MaPhieuGm")
                        .IsRequired()
                        .HasConstraintName("fk_PGM_CTGM");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaPhieuGmNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietHd", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHds")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("fk_HD_CTHD");

                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietHds")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MonAn_CTHD");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DatBan", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.BanAn", "MaBanNavigation")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .HasConstraintName("fk_DatBan_BanAn");

                    b.HasOne("ThanhThoaiRestaurant.Models.KhachHang", "MaKhNavigation")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .IsRequired()
                        .HasConstraintName("fk_DatBan_Khachhang");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DonHang", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "MaHdNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("fk_DonHang_HoaDon");

                    b.HasOne("ThanhThoaiRestaurant.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKH")
                        .IsRequired()
                        .HasConstraintName("fk_DonHang_Khachhang");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.GioHang", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.KhachHang", "MaKHNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaKH")
                        .IsRequired()
                        .HasConstraintName("FK_MaKH_MaMon");

                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_MonAn");

                    b.Navigation("MaKHNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.HoaDon", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.PhieuGiamGium", "MaPhieuGgNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPhieuGg")
                        .HasConstraintName("fk_HoaDon_PGG");

                    b.Navigation("MaPhieuGgNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.KhachHang", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.NguoiDung", "TenDangNhapNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("TenDangNhap")
                        .HasConstraintName("fk_TenDN1");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.MonAn", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.NhomMonAn", "MaNhomNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaNhom")
                        .HasConstraintName("fk_MaNhom");

                    b.HasOne("ThanhThoaiRestaurant.Models.GioHang", null)
                        .WithMany("MonAns")
                        .HasForeignKey("GioHangMaMon", "GioHangMaKH");

                    b.Navigation("MaNhomNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhanVien", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.NguoiDung", "TenDangNhapNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("TenDangNhap")
                        .HasConstraintName("fk_TenDN");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGoiMon", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.BanAn", "MaBanNavigation")
                        .WithMany("PhieuGoiMons")
                        .HasForeignKey("MaBan")
                        .HasConstraintName("fk_PhieuGoiMon_BanAn");

                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "MaHdNavigation")
                        .WithMany("PhieuGoiMons")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("fk_PhieuGoiMon_HoaDon");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.BanAn", b =>
                {
                    b.Navigation("PhieuGoiMons");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDhs");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.GioHang", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHds");

                    b.Navigation("DonHangs");

                    b.Navigation("PhieuGoiMons");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDhs");

                    b.Navigation("ChiTietGms");

                    b.Navigation("ChiTietHds");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NguoiDung", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhomMonAn", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGiamGium", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGoiMon", b =>
                {
                    b.Navigation("ChiTietGms");
                });
#pragma warning restore 612, 618
        }
    }
}
